### ISSUE TITLE
Error on "bundle install"

### ISSUE THREAD

**Issue by rodcul** [kodify/seo-tool#20]
[vagrant@localhost current]$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Using rake (10.1.0) 
Installing i18n (0.6.5) 
Errno::EACCES: Permission denied - /usr/local/rvm/gems/ruby-2.0.0-p247/bin
An error occurred while installing i18n (0.6.5), and Bundler cannot continue.
Make sure that `gem install i18n -v '0.6.5'` succeeds before bundling.

**Comment by natxo-kodify** [comment]
I had the same problem and it doesn't appear anymore changing permissions on that folder, didn't struggle much more, as its the dev machine, so security isn't a big issue. 

> sudo chmod 777 -R /usr/local/rvm/gems/

maybe @adriacidre can enlighten us a bit more :)

**Comment by rodcul** [comment]
hey @natxo-kodify can you include this in the readme and close the issue, thanks!

**Comment by rodcul** [comment]
(it seems to be working for me now)

**Comment by natxo-kodify** [comment]
sure!
