### ISSUE TITLE
domain_id is not informed although it WAS created

### ISSUE THREAD

**Issue by rodcul** [kodify/seo-tool#45]
Executing:

bundle exec rake crawl:domains

did not inform domain_id

> SELECT \* FROM seotool_dev.urls
> LIMIT 10

*******************\* 1. row *********************
              id: 1
       status_id: 
             url: http://url1.com
      created_at: 2013-11-25 14:24:40
      updated_at: 
  internal_links: 0
  external_links: 0
      visited_at: 
              ip: 
       subdomain: 
domain_authority: 
  page_authority: 
          source: 
       domain_id: 
*******************\* 2. row *********************
              id: 2
       status_id: 
             url: http://url2.com
      created_at: 2013-11-25 14:24:40
      updated_at: 2013-11-25 13:26:49
  internal_links: 0
  external_links: 0
      visited_at: 
              ip: 
       subdomain: 
domain_authority: 
  page_authority: 
          source: 
       domain_id: 2

**Comment by adriacidre** [comment]
Fixed
