### ISSUE TITLE
infinite loop: if url is not responding

### ISSUE THREAD

**Issue by rodcul** [kodify/seo-tool#46]
rodcul-mbp15-2:seo-tool rodcul$ bundle exec rake crawl:url
Processing http://blowjob.unix-fu.org/blowjob-porn/sweet-teen-maria-got-some-bitter-hard-gagging-132.html...
Could not open url: http://blowjob.unix-fu.org/blowjob-porn/sweet-teen-maria-got-some-bitter-hard-gagging-132.html
Processing http://www.blackcamz.nl...
Could not open url: http://www.blackcamz.nl
Processing http://www.blackcamz.nl...
Could not open url: http://www.blackcamz.nl
Processing http://www.blackcamz.nl...
Could not open url: http://www.blackcamz.nl
Processing http://www.blackcamz.nl...
Could not open url: http://www.blackcamz.nl
Processing http://www.blackcamz.nl...
Could not open url: http://www.blackcamz.nl
Processing http://www.blackcamz.nl...
Could not open url: http://www.blackcamz.nl
Processing http://www.blackcamz.nl...

**Comment by adriacidre** [comment]
This was fixed with https://github.com/kodify/seo-tool/pull/48
