### ISSUE TITLE
Save stats once per day

### ISSUE THREAD

**Issue by rodcul** [kodify/seo-tool#55]
Scenario: Save stats

Given 10 domains for site www.site1.com
and 5 are status empty
and 2 are status OK
and 3 are status remove
When stats cron is run once per 24 hours
Then www.site1.com is saved in site
and 5 are saved in status empty
and 2 are saved in status OK
and 3 are saved in status remove

**Comment by adriacidre** [comment]
There is no direct relation between domain and site, and it does not makes sense.
A site has many links related to it, as one link points to one site, btw its related domain can't have a related site, cause it can have links pointing to many sites, and theoretically have a different status foreach site.
So imho we should discuss a bit more about stats.

**Comment by rodcul** [comment]
Scenario: Save stats

Given 10 domains
and 5 are status empty
and 2 are status OK
and 3 are status remove
When stats cron is run once per 24 hours
Then 5 are saved in status empty
and 2 are saved in status OK
and 3 are saved in status remove

**Comment by adriacidre** [comment]
This will be fixed by : https://github.com/kodify/seo-tool/pull/59

**Comment by rodcul** [comment]
It looks like the stats for when status = empty are not being saved, is this possible? thanks

**Comment by adriacidre** [comment]
Yep is looping and calculating stats foreach status, but [Null] is not a valid status, I'll add a new status 'Empty' and set it as default, avoiding the usage of null.
